language: c

os:
  - linux
  - osx

sudo: required

compiler:
  - clang
  - gcc

before_install:
  - AA=autoconf-archive-2017.03.21
  - wget -O - http://ftpmirror.gnu.org/autoconf-archive/$AA.tar.xz | tar -xJ

before_script:
  - autoreconf -i -I $AA/m4

script:
  - ./configure && make && sudo make install
